Client/urls.py
from django.urls import path
from Client.views import *

urlpatterns = [
    path('', homeClient, name='homeClient'),
    path('addClient/', addClient, name='addClient'),
    path('detailClient/', detailClient, name='detailClient'),
    path('detailClient/<int:pk>/', detailClient, name='detailClient'),
    path('manageClient/', manageClient, name='manageClient')
]

EasyCompta/urls.py
from django.contrib import admin
from django.urls import path, include
from EasyCompta import views

urlpatterns = [
    path('', views.index),
    path('User/', include('User.urls')),
    path('Accounting/', include('Accounting.urls')),
    path('Client/', include('Client.urls')),
    path('admin/', admin.site.urls),
]

User/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('subscribe/', subscribe, name='subscribe'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('member/', member, name='member')
]

Client/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Client(models.Model) :
    client_nom = models.CharField(max_length=150)
    client_siret = models.CharField(max_length=30)
    client_adresse = models.CharField(max_length=255)
    client_cp = models.CharField(max_length=20)
    client_ville = models.CharField(max_length=60)
    username = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) :
        return "{} {} {} {} {}".format(
            self.client_nom,
            self.client_siret,
            self.client_adresse,
            self.client_cp,
            self.client_ville
        )

Client/forms.py
from django import forms
from Client.models import Client

class ClientForm(forms.ModelForm) :
    class Meta:
        model = Client
        fields = (
            'client_nom',
            'client_siret',
            'client_adresse',
            'client_cp',
            'client_ville'
        )

Client/views.py
import sys
from django.shortcuts import render, loader, get_object_or_404
from django.http import HttpResponseRedirect
from Client.forms import ClientForm
from Client.models import Client

# Create your views here.
def homeClient(request) :
    clients = Client.objects.all()
    context = {
        'clients': clients if len(clients) > 0 else 'Pas de clients.',
        'fileCss': sys._getframe().f_code.co_name
    }
    return render(request, 'homeClient.html', context)

def addClient(request) :
    if request.method == 'POST' :
        form = ClientForm(request.POST)
        if form.is_valid() :
            form.save()
            return HttpResponseRedirect('/Client/')
    
    form = ClientForm()
    context = {
        'form': form,
        'fileCss': sys._getframe().f_code.co_name
    }
    return render(request, 'addClient.html', context)

def detailClient(request, pk=0) :
    if pk > 0 :
        cl = get_object_or_404(Client, pk=pk)
        context = {
            'fileCss': sys._getframe().f_code.co_name,
            'client': cl
        }
        return render(request, 'detailClient.html', context)
    else :
        return HttpResponseRedirect('/Client/')

def manageClient(request) :
    pass

Client/templates/addClient.html
{% extends 'IndexIntegration.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <label for="id_client_nom">Nom : </label><br />
    {{ form.client_nom }} <br /><br />

    <label for="id_client_siret">N° Siret : </label><br />
    {{ form.client_siret }} <br /><br />

    <label for="id_client_adresse">Adresse : </label><br />
    {{ form.client_adresse }} <br /><br />

    <label for="id_client_cp">Code postal : </label><br />
    {{ form.client_cp }} <br /><br />

    <label for="id_client_ville">Ville : </label><br />
    {{ form.client_ville }}<br /><br />

    <input type="submit" value="Ajouter" />
</form>
{% endblock %}

Client/templates/detailClient.html
{% extends 'IndexIntegration.html' %}

{% block content %}
<div class="menu">
    <a href="/Client/">Mes clients</a>
    <a href="{% url 'addClient' %}">Ajouter un client</a>
    <a href="{% url 'manageClient' %}">Gérer mes clients</a>
</div>

<div class="desc">
    Nom du client : {{ client.client_nom}} <br />
    N° Siret : {{ client.client_siret }} <br />
    Adresse : {{ client.client_adresse }} <br />
    Code postal : {{ client.client_cp }} <br />
    Ville : {{ client.client_ville }}
</div>
{% endblock %}

Client/templates/homeClient.html
{% extends 'IndexIntegration.html' %}

{% block content %}
<div class="menu">
    <a href="{% url 'addClient' %}">Ajouter un client</a>
    <a href="{% url 'manageClient' %}">Gérer mes clients</a>
</div>

<div class="desc">
    Liste des clients : <br />
    {% if clients.client_nom|length > 0 %}
        {% for c in clients %}
            <a href="{% url 'detailClient' pk=c.pk %}">{{ c.client_nom }}</a><br />
        {% endfor %}
    {% else %}
        {{ clients }}
    {% endif %}
</div>
{% endblock %}